version: '3.11'

services:
  postgres:
    image: postgres:14-alpine
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: engl
    volumes:
      - "01-simple-alchemy-postgres:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: "no"
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - "01-simple-alchemy-pgadmin:/var/lib/pgadmin"
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:12345@postgres:5432/engl

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  01-simple-alchemy-pgadmin:
  01-simple-alchemy-postgres:
