version: '3.11'

services:
  postgres:
    image: postgres:14-alpine
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: engl

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - "01-simple-alchemy-postgres:/var/lib/postgresql/data"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:12345@postgres:5432/engl
    env_file:
      - .env

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["poetry", "run", "alembic", "upgrade", "head"]
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:12345@postgres:5432/engl
    volumes:
      - .:/app

volumes:
  01-simple-alchemy-pgadmin:
  01-simple-alchemy-postgres: