"""create table

Revision ID: 7d23af7daca2
Revises: 
Create Date: 2024-09-07 17:29:28.816858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d23af7daca2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('study_goal', sa.Text(), nullable=False),
    sa.Column('has_studied_before', sa.Boolean(), nullable=False),
    sa.Column('study_format', sa.Enum('ONLINE', 'OFFLINE', name='studyformatenum'), nullable=False),
    sa.Column('training_format', sa.Enum('GROUP', 'PAIR', 'INDIVIDUAL', name='trainingformatenum'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('tg_id', name=op.f('uq__users__tg_id')),
    sa.UniqueConstraint('username', name=op.f('uq__users__username'))
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=100), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('lesson_time', sa.Time(), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('lessons_user_id_fkey')),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], name=op.f('lessons_user_username_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__lessons'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    op.drop_table('users')
    # ### end Alembic commands ###
