"""update column user_username

Revision ID: 9fe7d221a61a
Revises: 7d23af7daca2
Create Date: 2024-09-07 17:41:41.083315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe7d221a61a'
down_revision: Union[str, None] = '7d23af7daca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lessons_user_username_fkey', 'lessons', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('lessons_user_username_fkey', 'lessons', 'users', ['user_username'], ['username'])
    # ### end Alembic commands ###
